sudo: required
language: python
python:
  - "3.6"
addons:
  apt:
    update: true
before_install:
  - sudo apt install sdcc
install:
  - "(cd vendor/libfx2/software && SDAR='sdcclib r' python setup.py install)"
script:
  - "(cd software && python setup.py install)"
  - "(cd software && python -m unittest discover -p '*')"
notifications:
  irc:
    channels:
      - "chat.freenode.net##openfpga"
    nick: openfpga-travis
    use_notice: true
    skip_join: true
